### ISSUE TITLE
Embedding context lengths

### ISSUE THREAD

**Issue by monneyboi** [resolve-works/insight#122]
```
worker-1  | INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 400 Bad Request"
worker-1  | ERROR:root:Could not process message
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/cli.py", line 70, in on_message
worker-1  |     embed_inode(body["after"]["id"], channel)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/tasks.py", line 266, in embed_inode
worker-1  |     for embedding, page in zip(embeddings, pages):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 39, in embed
worker-1  |     raise Exception(response.text)
worker-1  | Exception: {
worker-1  |   "error": {
worker-1  |     "message": "This model's maximum context length is 8192 tokens, however you requested 10839 tokens (10839 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.",
worker-1  |     "type": "invalid_request_error",
worker-1  |     "param": null,
worker-1  |     "code": null
worker-1  |   }
worker-1  | }
```

**Comment by monneyboi** [comment]
Some PDF pages have a lot of text. The 2 PDFs that i found were poster format with 11pt text in a huge table. We now cut the tokens at the 8192 maximum as this happens very rarely and there's a lot of information about the page in those tokens.

If embedding model context increases in the future, we can remove this limitation.
