### ISSUE TITLE
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)

### ISSUE THREAD

**Issue by monneyboi** [resolve-works/insight#123]
```
worker-1  | INFO:root:Embedding inode 2076
worker-1  | thread '<unnamed>' panicked at src/lib.rs:243:33:
worker-1  | called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)
worker-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
worker-1  | ERROR:pika.adapters.utils.io_services_utils:Wrapped func exited with exception. Caller's stack:
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
worker-1  |     return func(*args, **kwargs)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 1047, in _on_socket_readable
worker-1  |     self._consume()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 801, in _consume
worker-1  |     self._protocol.data_received(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/base_connection.py", line 465, in _proto_data_received
worker-1  |     self._on_data_available(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1973, in _on_data_available
worker-1  |     self._process_frame(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 2139, in _process_frame
worker-1  |     self._deliver_frame_to_channel(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1619, in _deliver_frame_to_channel
worker-1  |     self._channels[value.channel_number]._handle_content_frame(value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1024, in _handle_content_frame
worker-1  |     self._on_deliver(*response)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1158, in _on_deliver
worker-1  |     self._consumers[consumer_tag](self, method_frame.method,
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/cli.py", line 70, in on_message
worker-1  |     embed_inode(body["after"]["id"], channel)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/tasks.py", line 266, in embed_inode
worker-1  |     for embedding, page in zip(embeddings, pages):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in embed
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in <listcomp>
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/tiktoken/core.py", line 120, in encode
worker-1  |     return self._core_bpe.encode(text, allowed_special)
worker-1  | pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
worker-1  |     return func(*args, **kwargs)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 1047, in _on_socket_readable
worker-1  |     self._consume()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 801, in _consume
worker-1  |     self._protocol.data_received(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/base_connection.py", line 465, in _proto_data_received
worker-1  |     self._on_data_available(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1973, in _on_data_available
worker-1  |     self._process_frame(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 2139, in _process_frame
worker-1  |     self._deliver_frame_to_channel(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1619, in _deliver_frame_to_channel
worker-1  |     self._channels[value.channel_number]._handle_content_frame(value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1024, in _handle_content_frame
worker-1  |     self._on_deliver(*response)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1158, in _on_deliver
worker-1  |     self._consumers[consumer_tag](self, method_frame.method,
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/cli.py", line 70, in on_message
worker-1  |     embed_inode(body["after"]["id"], channel)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/tasks.py", line 266, in embed_inode
worker-1  |     for embedding, page in zip(embeddings, pages):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in embed
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in <listcomp>
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/tiktoken/core.py", line 120, in encode
worker-1  |     return self._core_bpe.encode(text, allowed_special)
worker-1  | pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/bin/insight-worker", line 8, in <module>
worker-1  |     sys.exit(cli())
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
worker-1  |     return self.main(*args, **kwargs)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
worker-1  |     rv = self.invoke(ctx)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
worker-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
worker-1  |     return ctx.invoke(self.callback, **ctx.params)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
worker-1  |     return __callback(*args, **kwargs)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/cli.py", line 159, in process_messages
worker-1  |     connection.ioloop.start()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/select_connection.py", line 546, in start
worker-1  |     self._poller.start()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/select_connection.py", line 806, in start
worker-1  |     self.poll()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/select_connection.py", line 1203, in poll
worker-1  |     self._dispatch_fd_events(fd_event_map)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/select_connection.py", line 907, in _dispatch_fd_events
worker-1  |     handler(fileno, events)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 402, in _on_reader_writer_fd_events
worker-1  |     callbacks.reader()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
worker-1  |     return func(*args, **kwargs)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 1047, in _on_socket_readable
worker-1  |     self._consume()
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/utils/io_services_utils.py", line 801, in _consume
worker-1  |     self._protocol.data_received(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/adapters/base_connection.py", line 465, in _proto_data_received
worker-1  |     self._on_data_available(data)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1973, in _on_data_available
worker-1  |     self._process_frame(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 2139, in _process_frame
worker-1  |     self._deliver_frame_to_channel(frame_value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/connection.py", line 1619, in _deliver_frame_to_channel
worker-1  |     self._channels[value.channel_number]._handle_content_frame(value)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1024, in _handle_content_frame
worker-1  |     self._on_deliver(*response)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/pika/channel.py", line 1158, in _on_deliver
worker-1  |     self._consumers[consumer_tag](self, method_frame.method,
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/cli.py", line 70, in on_message
worker-1  |     embed_inode(body["after"]["id"], channel)
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/tasks.py", line 266, in embed_inode
worker-1  |     for embedding, page in zip(embeddings, pages):
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in embed
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/insight_worker/rag.py", line 26, in <listcomp>
worker-1  |     "input": [encoding.encode(string) for string in batch],
worker-1  |   File "/usr/local/lib/python3.10/dist-packages/tiktoken/core.py", line 120, in encode
worker-1  |     return self._core_bpe.encode(text, allowed_special)
worker-1  | pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)
worker-1 exited with code 1
```

**Comment by monneyboi** [comment]
This was caused by a bizarre amount of whitespace in the middle of a string. Now we're stripping excess whitespace.
