### ISSUE TITLE
insightclient service account token refresh

### ISSUE THREAD

**Issue by monneyboi** [resolve-works/insight#125]
```
asktheeu-trfz7: Traceback (most recent call last):
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 528, in request
asktheeu-trfz7:     url, headers, data = self._client.add_token(
asktheeu-trfz7:                          ~~~~~~~~~~~~~~~~~~~~~~^
asktheeu-trfz7:         url, http_method=method, body=data, headers=headers
asktheeu-trfz7:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:     )
asktheeu-trfz7:     ^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
asktheeu-trfz7:     raise TokenExpiredError()
asktheeu-trfz7: oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
asktheeu-trfz7:
asktheeu-trfz7: During handling of the above exception, another exception occurred:
asktheeu-trfz7:
asktheeu-trfz7: Traceback (most recent call last):
asktheeu-trfz7:   File "/usr/src/app/./scrape.py", line 72, in <module>
asktheeu-trfz7:     insight.create_file(name, size, stream, parent["id"], is_public=True)
asktheeu-trfz7:     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/insightclient/client.py", line 112, in create_file
asktheeu-trfz7:     inode = self.create_inode(name, InodeType.FILE, parent_id, is_public)
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/insightclient/client.py", line 59, in create_inode
asktheeu-trfz7:     response = self.post(
asktheeu-trfz7:         os.path.join(config.get("api", "endpoint"), "inodes"),
asktheeu-trfz7:     ...<6 lines>...
asktheeu-trfz7:         headers={"Prefer": "return=representation"},
asktheeu-trfz7:     )
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
asktheeu-trfz7:     return self.request("POST", url, data=data, json=json, **kwargs)
asktheeu-trfz7:            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 547, in request
asktheeu-trfz7:     token = self.refresh_token(
asktheeu-trfz7:         self.auto_refresh_url, auth=auth, **kwargs
asktheeu-trfz7:     )
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 496, in refresh_token
asktheeu-trfz7:     self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
asktheeu-trfz7:                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
asktheeu-trfz7:     self.token = parse_token_response(body, scope=scope)
asktheeu-trfz7:                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
asktheeu-trfz7:     validate_token_parameters(params)
asktheeu-trfz7:     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
asktheeu-trfz7:     raise_from_error(params.get('error'), params)
asktheeu-trfz7:     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asktheeu-trfz7:   File "/usr/local/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
asktheeu-trfz7:     raise cls(**kwargs)
asktheeu-trfz7: oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Invalid client or Invalid client credentials
asktheeu-trfz7: time="2024-12-04T20:23:29.153Z" level=info msg="sub-process exited" argo=true error="<nil>"
asktheeu-trfz7: Error: exit status 1
```

It seems that token refresh for service account clients is not working.

**Comment by monneyboi** [comment]
Client now has refresh logic that makes use of the `BackendApplication` client logic.
